### ISSUE TITLE
Image paths

### ISSUE THREAD

**Issue by hartpableo** [rckash/blue-site#3]
![image](https://github.com/user-attachments/assets/17c9eb26-6afc-4b54-b6d2-f0ccd30ab933)

Image not displaying due to pathing errors.

**Comment by rckash** [comment]
I have update the image path. The image is not the same tint as that of in the design. How do I change it to have the same tint?

**Comment by hartpableo** [comment]
since you're adding the image via css background, you can try adding a ::before pseudo-element to your block

the key here is the ::before element's background color and opacity

![image](https://github.com/user-attachments/assets/682ec20e-68fa-4235-a8b3-c909d48927b6)

(just follow the right colors used in the design, my blue was just for demo purposes)
