### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by hartpableo** [rckash/blue-site#5]
![image](https://github.com/user-attachments/assets/4c54ee5f-8d01-4aa7-ab8d-d48730fcba37)

Try to put all the cards in a single wrapper instead of grouping them by rows.

This is 99% how it should be structured as in most cases these cards are dynamically generated from specific content types on the site/database.

Let me know if you need more explanation here.

**Comment by rckash** [comment]
Yes, more explanation would be great. How do I implement it using flex?

**Comment by hartpableo** [comment]
@rckash remove the .row-big-gap so that your crew cards are all siblings.

The use flex-wrap: wrap; on your flex wrapper which is the .grid-small__cards
